from __future__ import annotations

import base64
import binascii
import logging
import os
import random
import tempfile
from dataclasses import dataclass
from pathlib import Path

from yt_dlp import YoutubeDL
from yt_dlp.utils import DownloadError, download_range_func

logger = logging.getLogger(__name__)

_ARABIC_QUERIES = (
    "اغاني عربية official audio",
    "Arabic pop official audio",
    "Arabic indie official audio",
    "Arabic hit song official video",
)

_FOREIGN_QUERIES = (
    "English pop official audio",
    "international pop official audio",
    "indie pop official audio",
    "pop hit song official video",
)

_BAD_TITLE_PARTS = (
    "karaoke",
    "slowed",
    "reverb",
    "nightcore",
    "sped up",
    "8d audio",
    "instrumental",
    "cover",
    "remix",
    "reaction",
    "lyrics only",
    "ai generated",
    "generated by ai",
    "suno",
    "udio",
)


@dataclass(frozen=True, slots=True)
class YouTubeTrack:
    path: Path
    title: str
    webpage_url: str


@dataclass(frozen=True, slots=True)
class _ClientMode:
    name: str
    extractor_args: dict[str, dict[str, list[str]]]
    allow_cookies: bool = True


class YouTubeStoryMusic:
    """Pick a real YouTube track using multiple extraction strategies."""

    def __init__(
        self,
        *,
        cookie_file: Path | None = None,
        cookies_b64: str | None = None,
        pot_provider_home: Path | None = None,
        attempts: int = 3,
    ):
        self._temporary_cookie_file: Path | None = None
        self.cookie_file = self._resolve_cookie_file(cookie_file, cookies_b64)
        self.pot_provider_home = (
            pot_provider_home
            if pot_provider_home and pot_provider_home.is_dir()
            else None
        )
        self.attempts = max(1, min(int(attempts), 6))
        self._random = random.SystemRandom()

    def _resolve_cookie_file(
        self,
        cookie_file: Path | None,
        cookies_b64: str | None,
    ) -> Path | None:
        if cookies_b64:
            compact = "".join(cookies_b64.split())
            try:
                raw = base64.b64decode(compact, validate=True)
            except (binascii.Error, ValueError) as error:
                raise RuntimeError(
                    "STORY_YOUTUBE_COOKIES_B64 is not valid Base64"
                ) from error
            try:
                text = raw.decode("utf-8-sig")
            except UnicodeDecodeError as error:
                raise RuntimeError(
                    "STORY_YOUTUBE_COOKIES_B64 must contain a UTF-8 cookies.txt file"
                ) from error

            normalized = text.replace("\r\n", "\n").replace("\r", "\n")
            first = normalized.split("\n", 1)[0].strip()
            if first not in {
                "# Netscape HTTP Cookie File",
                "# HTTP Cookie File",
            }:
                raise RuntimeError(
                    "STORY_YOUTUBE_COOKIES_B64 must be a Netscape cookies.txt file"
                )

            fd, raw_path = tempfile.mkstemp(
                prefix="streak-youtube-cookies-",
                suffix=".txt",
            )
            path = Path(raw_path)
            try:
                os.fchmod(fd, 0o600)
                with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as output:
                    output.write(normalized)
                    if not normalized.endswith("\n"):
                        output.write("\n")
            except Exception:
                path.unlink(missing_ok=True)
                raise
            self._temporary_cookie_file = path
            logger.info("STORY_YOUTUBE_COOKIES_READY source=railway_secret")
            return path

        if cookie_file and cookie_file.is_file():
            logger.info("STORY_YOUTUBE_COOKIES_READY source=file")
            return cookie_file

        logger.warning("STORY_YOUTUBE_COOKIES_MISSING")
        return None

    def close(self) -> None:
        if self._temporary_cookie_file is None:
            return
        try:
            self._temporary_cookie_file.unlink(missing_ok=True)
        except OSError:
            logger.debug(
                "STORY_YOUTUBE_COOKIE_CLEANUP_FAILED path=%s",
                self._temporary_cookie_file,
            )
        finally:
            self._temporary_cookie_file = None

    def _modes(self) -> tuple[_ClientMode, ...]:
        modes: list[_ClientMode] = []
        if self.pot_provider_home is not None:
            modes.append(
                _ClientMode(
                    "mweb-pot",
                    {
                        "youtube": {
                            "player_client": ["mweb", "default"],
                        },
                        "youtubepot-bgutilscript": {
                            "server_home": [str(self.pot_provider_home)],
                        },
                    },
                )
            )
        modes.extend(
            (
                _ClientMode(
                    "web-safari",
                    {"youtube": {"player_client": ["web_safari"]}},
                ),
                _ClientMode(
                    "android-vr",
                    {"youtube": {"player_client": ["android_vr"]}},
                    allow_cookies=False,
                ),
                _ClientMode("default", {}),
            )
        )
        return tuple(modes)

    def _base_options(self, mode: _ClientMode) -> dict:
        options = {
            "quiet": True,
            "no_warnings": True,
            "noplaylist": True,
            "retries": 2,
            "fragment_retries": 2,
            "socket_timeout": 20,
            "source_address": "0.0.0.0",
        }
        if mode.extractor_args:
            options["extractor_args"] = mode.extractor_args
        if self.cookie_file and mode.allow_cookies:
            options["cookiefile"] = str(self.cookie_file)
        return options

    @staticmethod
    def _valid_entry(entry: dict) -> bool:
        if not entry or entry.get("live_status") in {"is_live", "is_upcoming"}:
            return False
        duration = entry.get("duration")
        if duration is not None:
            try:
                seconds = float(duration)
            except (TypeError, ValueError):
                return False
            if seconds < 45 or seconds > 900:
                return False
        title = str(entry.get("title") or "").casefold()
        return bool(title) and not any(part in title for part in _BAD_TITLE_PARTS)

    @staticmethod
    def _brief_error(error: Exception) -> str:
        message = " ".join(str(error).split())
        return message[:500] or error.__class__.__name__

    def _search(self, query: str) -> list[dict]:
        last_error: Exception | None = None
        for mode in self._modes():
            options = self._base_options(mode)
            options.update(
                {
                    "extract_flat": "in_playlist",
                    "skip_download": True,
                    "playlistend": 8,
                }
            )
            try:
                with YoutubeDL(options) as ydl:
                    result = ydl.extract_info(f"ytsearch8:{query}", download=False)
                entries = (result or {}).get("entries") or []
                valid = [entry for entry in entries if self._valid_entry(entry)]
                if valid:
                    logger.info(
                        "STORY_YOUTUBE_SEARCH_OK mode=%s query=%r results=%s",
                        mode.name,
                        query,
                        len(valid),
                    )
                    return valid
            except Exception as error:
                last_error = error
                logger.warning(
                    "STORY_YOUTUBE_SEARCH_MODE_FAILED mode=%s query=%r error=%s",
                    mode.name,
                    query,
                    self._brief_error(error),
                )
        if last_error:
            raise DownloadError(self._brief_error(last_error))
        return []

    def _download_with_mode(
        self,
        entry: dict,
        directory: Path,
        duration: int,
        mode: _ClientMode,
    ) -> YouTubeTrack:
        video_id = str(entry.get("id") or "").strip()
        webpage_url = str(entry.get("webpage_url") or "").strip()
        if not webpage_url and video_id:
            webpage_url = f"https://www.youtube.com/watch?v={video_id}"
        if not webpage_url:
            raise DownloadError("search result has no YouTube URL")

        total = float(entry.get("duration") or 180)
        clip_length = min(float(duration) + 1.0, max(3.0, total - 1.0))
        latest = max(0.0, total - clip_length - 2.0)
        if latest <= 8:
            start = 0.0
        else:
            low = min(latest, max(8.0, total * 0.25))
            high = min(latest, max(low, total * 0.65))
            start = self._random.uniform(low, high) if high > low else low
        end = min(total, start + clip_length)

        safe_mode = mode.name.replace("-", "_")
        output_template = str(directory / f"youtube-{safe_mode}-%(id)s.%(ext)s")
        options = self._base_options(mode)
        options.update(
            {
                "format": "bestaudio/best",
                "outtmpl": output_template,
                "download_ranges": download_range_func(None, [(start, end)]),
                "force_keyframes_at_cuts": True,
            }
        )

        before = set(directory.glob(f"youtube-{safe_mode}-*"))
        with YoutubeDL(options) as ydl:
            info = ydl.extract_info(webpage_url, download=True)
            prepared = Path(ydl.prepare_filename(info))

        if prepared.is_file():
            path = prepared
        else:
            created = [
                item
                for item in directory.glob(f"youtube-{safe_mode}-*")
                if item not in before and item.is_file()
            ]
            if not created:
                raise DownloadError("yt-dlp did not create the requested audio clip")
            path = max(created, key=lambda item: item.stat().st_mtime)

        title = str((info or {}).get("title") or entry.get("title") or "YouTube")
        url = str((info or {}).get("webpage_url") or webpage_url)
        logger.info(
            "STORY_YOUTUBE_DOWNLOAD_OK mode=%s title=%r url=%s",
            mode.name,
            title,
            url,
        )
        return YouTubeTrack(path=path, title=title, webpage_url=url)

    def _download_clip(
        self,
        entry: dict,
        directory: Path,
        duration: int,
    ) -> YouTubeTrack:
        last_error: Exception | None = None
        for mode in self._modes():
            try:
                return self._download_with_mode(entry, directory, duration, mode)
            except Exception as error:
                last_error = error
                logger.warning(
                    "STORY_YOUTUBE_DOWNLOAD_MODE_FAILED mode=%s title=%r error=%s",
                    mode.name,
                    entry.get("title"),
                    self._brief_error(error),
                )
        raise RuntimeError(
            "كل طرق استخراج YouTube فشلت: "
            + (self._brief_error(last_error) if last_error else "unknown error")
        ) from last_error

    def fetch(self, directory: Path, duration: int) -> YouTubeTrack:
        directory.mkdir(parents=True, exist_ok=True)
        last_error: Exception | None = None
        pools = (_ARABIC_QUERIES, _FOREIGN_QUERIES)

        if self.pot_provider_home is None:
            logger.warning(
                "STORY_YOUTUBE_POT_PROVIDER_UNAVAILABLE fallback_modes=web-safari,android-vr,default"
            )

        for _ in range(self.attempts):
            query = self._random.choice(self._random.choice(pools))
            try:
                candidates = self._search(query)
                if not candidates:
                    raise DownloadError(f"no suitable search results for {query}")
                self._random.shuffle(candidates)
                for candidate in candidates[:3]:
                    try:
                        return self._download_clip(candidate, directory, duration)
                    except Exception as error:
                        last_error = error
            except Exception as error:
                last_error = error
                logger.warning(
                    "STORY_YOUTUBE_ATTEMPT_FAILED query=%r error=%s",
                    query,
                    self._brief_error(error),
                )

        detail = self._brief_error(last_error) if last_error else "unknown error"
        if "sign in to confirm you’re not a bot" in detail.casefold() or "sign in to confirm you're not a bot" in detail.casefold():
            logger.error(
                "STORY_YOUTUBE_AUTH_REQUIRED cookies_configured=%s",
                bool(self.cookie_file),
            )
        logger.error("STORY_YOUTUBE_ALL_FAILED error=%s", detail)
        raise RuntimeError(f"تعذر جلب أغنية من YouTube: {detail}") from last_error
