from __future__ import annotations

import logging
import random
from dataclasses import dataclass
from pathlib import Path

from yt_dlp import YoutubeDL
from yt_dlp.utils import DownloadError, download_range_func

logger = logging.getLogger(__name__)

_ARABIC_QUERIES = (
    "اغاني عربية official audio",
    "Arabic pop official audio",
    "Arabic indie official audio",
    "Arabic hit song official video",
)

_FOREIGN_QUERIES = (
    "English pop official audio",
    "international pop official audio",
    "indie pop official audio",
    "pop hit song official video",
)

_BAD_TITLE_PARTS = (
    "karaoke",
    "slowed",
    "reverb",
    "nightcore",
    "sped up",
    "8d audio",
    "instrumental",
    "cover",
    "remix",
    "reaction",
    "lyrics only",
    "ai generated",
    "generated by ai",
    "suno",
    "udio",
)


@dataclass(frozen=True, slots=True)
class YouTubeTrack:
    path: Path
    title: str
    webpage_url: str


class YouTubeStoryMusic:
    """Pick a random real YouTube track and download only the needed short clip."""

    def __init__(
        self,
        *,
        cookie_file: Path | None = None,
        attempts: int = 3,
    ):
        self.cookie_file = cookie_file if cookie_file and cookie_file.is_file() else None
        self.attempts = max(1, min(int(attempts), 6))
        self._random = random.SystemRandom()

    def _base_options(self) -> dict:
        options = {
            "quiet": True,
            "no_warnings": True,
            "noplaylist": True,
            "retries": 2,
            "fragment_retries": 2,
            "socket_timeout": 20,
        }
        if self.cookie_file:
            options["cookiefile"] = str(self.cookie_file)
        return options

    @staticmethod
    def _valid_entry(entry: dict) -> bool:
        if not entry or entry.get("live_status") in {"is_live", "is_upcoming"}:
            return False
        duration = entry.get("duration")
        if duration is not None:
            try:
                seconds = float(duration)
            except (TypeError, ValueError):
                return False
            if seconds < 45 or seconds > 900:
                return False
        title = str(entry.get("title") or "").casefold()
        return bool(title) and not any(part in title for part in _BAD_TITLE_PARTS)

    def _search(self, query: str) -> list[dict]:
        options = self._base_options()
        options.update(
            {
                "extract_flat": "in_playlist",
                "skip_download": True,
                "playlistend": 8,
            }
        )
        with YoutubeDL(options) as ydl:
            result = ydl.extract_info(f"ytsearch8:{query}", download=False)
        entries = (result or {}).get("entries") or []
        return [entry for entry in entries if self._valid_entry(entry)]

    def _download_clip(
        self,
        entry: dict,
        directory: Path,
        duration: int,
    ) -> YouTubeTrack:
        video_id = str(entry.get("id") or "").strip()
        webpage_url = str(entry.get("webpage_url") or "").strip()
        if not webpage_url and video_id:
            webpage_url = f"https://www.youtube.com/watch?v={video_id}"
        if not webpage_url:
            raise DownloadError("search result has no YouTube URL")

        total = float(entry.get("duration") or 180)
        clip_length = min(float(duration) + 1.0, max(3.0, total - 1.0))
        latest = max(0.0, total - clip_length - 2.0)
        if latest <= 8:
            start = 0.0
        else:
            # Skip intros when possible and favor the middle of the song.
            low = min(latest, max(8.0, total * 0.25))
            high = min(latest, max(low, total * 0.65))
            start = self._random.uniform(low, high) if high > low else low
        end = min(total, start + clip_length)

        output_template = str(directory / "youtube-%(id)s.%(ext)s")
        options = self._base_options()
        options.update(
            {
                "format": "bestaudio/best",
                "outtmpl": output_template,
                "download_ranges": download_range_func(None, [(start, end)]),
                "force_keyframes_at_cuts": True,
            }
        )
        before = set(directory.glob("youtube-*"))
        with YoutubeDL(options) as ydl:
            info = ydl.extract_info(webpage_url, download=True)
            prepared = Path(ydl.prepare_filename(info))
        if prepared.is_file():
            path = prepared
        else:
            created = [item for item in directory.glob("youtube-*") if item not in before]
            if not created:
                raise DownloadError("yt-dlp did not create the requested audio clip")
            path = max(created, key=lambda item: item.stat().st_mtime)

        title = str((info or {}).get("title") or entry.get("title") or "YouTube")
        url = str((info or {}).get("webpage_url") or webpage_url)
        return YouTubeTrack(path=path, title=title, webpage_url=url)

    def fetch(self, directory: Path, duration: int) -> YouTubeTrack:
        directory.mkdir(parents=True, exist_ok=True)
        last_error: Exception | None = None
        pools = (_ARABIC_QUERIES, _FOREIGN_QUERIES)

        for _ in range(self.attempts):
            # 50/50 Arabic / foreign without showing a choice to the user.
            query = self._random.choice(self._random.choice(pools))
            try:
                candidates = self._search(query)
                if not candidates:
                    raise DownloadError(f"no suitable search results for {query}")
                self._random.shuffle(candidates)
                for candidate in candidates[:3]:
                    try:
                        track = self._download_clip(candidate, directory, duration)
                        logger.info(
                            "STORY_YOUTUBE_MUSIC_SELECTED title=%r url=%s",
                            track.title,
                            track.webpage_url,
                        )
                        return track
                    except Exception as error:
                        last_error = error
                        logger.warning(
                            "STORY_YOUTUBE_MUSIC_CANDIDATE_FAILED query=%r error=%s",
                            query,
                            error,
                        )
            except Exception as error:
                last_error = error
                logger.warning(
                    "STORY_YOUTUBE_MUSIC_SEARCH_FAILED query=%r error=%s",
                    query,
                    error,
                )

        raise RuntimeError("تعذر جلب أغنية من YouTube") from last_error
